USE [blogdb]
GO

CREATE TABLE [dbo].Users (
	[Id] BIGINT IDENTITY(1,1) NOT NULL,
	[Username] NVARCHAR(4000) NOT NULL,
	[FirstName] NVARCHAR(4000) NOT NULL,
	[LastName] NVARCHAR(4000) NOT NULL,
	PRIMARY KEY ([Id])
);

GO

CREATE TABLE [dbo].[Roles] (
	[Id] BIGINT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(200) NOT NULL,
	[UserId] BIGINT NOT NULL,
	PRIMARY KEY ([Id])
);

GO

CREATE TABLE [dbo].[Tasks] (
	[Id] BIGINT IDENTITY(1,1) NOT NULL,
	[Title] NVARCHAR(200) NOT NULL,
	[Description] NVARCHAR(200) NOT NULL,
	[Priority] INT NOT NULL,
	[UserId] BIGINT NOT NULL,
	PRIMARY KEY ([Id])
);

GO

ALTER TABLE [dbo].[Roles]
	ADD CONSTRAINT FK_Roles_Users FOREIGN KEY (UserId)
	REFERENCES [dbo].[Users] (Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO

ALTER TABLE [dbo].[Tasks]
	ADD CONSTRAINT FK_Tasks_Users FOREIGN KEY (UserId)
	REFERENCES [dbo].[Users] (Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

GO